######################################################
#             Hidden TV Show Collections             #
######################################################

templates:
  hidden:
    optional:
      - sort 
    tmdb_show: <<show>>
    minimum_items: 1
    collection_mode: hide
    sort_title: <<sort>>

collections:
  "Bob's Burgers":
    template: {name: hidden, show: 32726}
  Downton Abbey:
    template: {name: hidden, show: 33907}
  Family Guy:
    template: {name: hidden, show: 1434}
  Flowers in the Attic:
    template: {name: hidden, show: 203728}
  The Full Monty:
    template: {name: hidden, show: 196214, sort: Full Monty}
  Futurama:
    template: {name: hidden, show: 615}
  The Good Witch:
    template: {name: hidden, show: 61864, sort: Good Witch}
  "Hey Arnold!":
    template: {name: hidden, show: 537}
  Jurassic Park:
    template: {name: hidden, show: 93741}
  Middle-Earth:
    template: {name: hidden, show: 84773}
  PAW Patrol:
    template: {name: hidden, show: 57532}
  Pok√©mon:
    template: {name: hidden, show: 60572}
  The Simpsons:
    template: {name: hidden, show: 456, sort: Simpsons}
  Scott Pilgrim:
    template: {name: hidden, show: 155292}
  South Park:
    template: {name: hidden, show: 2190}
  SpongeBob SquarePants:
    template: {name: hidden, show: 387}
