######################################################
#                    TV Overlays                     #
######################################################
      
overlays:
  The Simpsons Top 100:
    overlay:
      name: IMDb-Top-100
    imdb_list: 
      url: https://www.imdb.com/search/title/?series=tt0096697&sort=user_rating,desc
      limit: 100
    builder_level: episode

  South Park Top 100:
    overlay:
      name: IMDb-Top-100
    imdb_list: 
      url: https://www.imdb.com/search/title/?series=tt0121955&sort=user_rating,desc
      limit: 100
    builder_level: episode
